# fly.toml app configuration file generated for nameless-sky-4121 on 2023-10-16T06:35:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nameless-sky-4121"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
